project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true 
  eval: true
  
website:
  title: pkgsite
  navbar:
    left:
      - sidebar:articles
      - href: reference/index.qmd
        text: Reference  
    right:
      - icon: github
        href: https://github.com/edgararuiz/pkgsite

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Setup GitHub Pages"
        href: articles/github-actions.qmd
      - text: "Customize Pages"
        href: articles/customize.qmd        
      
format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    eval: true
    freeze: true
    css: site/styles.css
    theme:
      light: [cosmo, site/theme.scss]
      dark: [cosmo, site/theme-dark.scss]
        
pkgsite: 
  dir: "."
  reference:
    dir: reference
    template: inst/templates/_reference.qmd
    not_run_examples: true
    index:
      file: index.qmd
      template: inst/templates/_index.qmd
      contents:
        - section: Quarto file creation
          contents: 
          - write_reference
          - write_reference_index.qmd
          - write_reference_pages.qmd
        - section: Conversion functions
          contents:
          - index_to_qmd.qmd
          - rd_to_qmd.qmd
          - rd_to_list.qmd
