project:
  type: website
  output-dir: docs
  post-render: _post-render.R
  
execute:
  freeze: true
  eval: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

website:
  title: pkgsite
  site-url: https://edgararuiz.github.io/pkgsite
  favicon: "site/images/favicon/apple-touch-icon.png"
  navbar:
    logo: "site/images/favicon/apple-touch-icon.png"
    left:
      - sidebar:articles
      - href: reference/index.qmd
        text: Reference  
      - href: changelog.qmd
        text: News
    right:
      - icon: github
        href: https://github.com/edgararuiz/pkgsite

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Building a full website"
        href: articles/quarto-website.qmd
      - text: "Setup GitHub Pages"
        href: articles/github-actions.qmd
      - text: "Customize Pages"
        href: articles/customize.qmd
      
format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    eval: true
    freeze: true
    css: site/styles.css
    theme:
      light: [cosmo, site/theme.scss]
      dark: [cosmo, site/theme-dark.scss]
        
pkgsite: 
  dir: "."
  reference:
    dir: reference
    template: inst/templates/_reference.qmd
    not_run_examples: true
    index:
      file: index.qmd
      template: inst/templates/_index.qmd
      contents:
        - section: Write functions
          contents:
            - write_reference
            - write_reference_index
            - write_reference_pages
        - section: Conversion functions
          contents:
            - index_to_qmd
            - rd_to_list
            - rd_to_qmd
      
