project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true 
  eval: true
  
website:
  title: pkgsite
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference  
    right:
      - icon: github
        href: https://github.com/edgararuiz/pkgsite
format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    eval: true
    freeze: true
    css: site/styles.css
    theme:
      light: [cosmo, site/theme.scss]
      dark: [cosmo, site/theme-dark.scss]
        
pkgsite: 
    dir: "."
    reference:
      dir: reference
      template: inst/templates/_reference.qmd
      not_run_examples: true
      index:
        file: index.qmd
        template: inst/templates/_index.qmd
        contents:
          sections:
            - title: Quarto file creation
              contents: 
              - write_reference
              - write_reference_index
              - write_reference_pages
            - title: Conversion functions
              contents:
              - index_to_qmd
              - rd_to_qmd
              - rd_to_list
