project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true 
  eval: true
  
website:
  title: pkgsite
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference  
  
pkgsite: 
    dir: "."
    reference:
      dir: reference
      template: inst/templates/_reference.qmd
      not_run_examples: true
      index:
        file: index.qmd
        template: inst/templates/_index.qmd
        contents:
          - write_reference
          - rd_to_qmd
