---
title: "Create a Quarto file that lists the available reference pages"
execute:
  eval: true
  freeze: true
---

## index_to_qmd

## Description
Create a Quarto file that lists the available reference pages


## Usage
```r
index_to_qmd(pkg = ".", template = NULL, quarto_file_path = NULL)
```

## Arguments
|Arguments|Description|
|---|---|
| pkg | Path to the root of the R package. Defaults to `"."`. |
| template | The path to a Quarto file that can be used as the template for all of the resulting reference files. If left NULL, `pkgsite` will use its default template. |
| quarto_file_path | Path to the folder containing _quarto.yml. Use when the Quarto project root differs from the package root (e.g. the package lives in a sub-folder of a larger Quarto project). Must be a directory path. Defaults to `NULL`, in which case `pkg` is used. |


## Value
A character vector with the contents of a document that links to the converted Quarto documents.





## See Also
Other Conversion functions: `rd_to_list()`, `rd_to_qmd()`

## Examples
```{r}
library(pkgsite)
example_pkg <- system.file("example", package = "pkgsite")
index_to_qmd(pkg = example_pkg)
```
