---
title: "Converts 'Rd' to Quarto files"
execute:
  eval: true
  freeze: true
---

[R/rd-to-qmd.R](https://github.com/edgararuiz/pkgsite/blob/main/R/rd-to-qmd.R)

## rd_to_qmd

## Description
Converts 'Rd' to Quarto files


## Usage
```r
rd_to_qmd(
  path,
  pkg = ".",
  examples = TRUE,
  not_run_examples = FALSE,
  template = NULL,
  quarto_file_path = NULL
)
```

## Arguments
|Arguments|Description|
|---|---|
| path | The path to the source Rd file |
| pkg | Path to the root of the R package. Defaults to `"."`. |
| examples | Flag that sets the examples code chunk to be evaluated when the Quarto document is rendered |
| not_run_examples | Flag that sets the "do not run" examples code chunk to be evaluated when the Quarto document is rendered |
| template | The path to a Quarto file that can be used as the template for all of the resulting reference files. If left NULL, `pkgsite` will use its default template. |
| quarto_file_path | Path to the folder containing _quarto.yml. Use when the Quarto project root differs from the package root (e.g. the package lives in a sub-folder of a larger Quarto project). Must be a directory path. Defaults to `NULL`, in which case `pkg` is used. |



## Value
A character vector with the resulting contents of converting the Rd file format into a Quarto file format.


## Examples
```{r}
library(pkgsite)
example_pkg <- system.file("example", package = "pkgsite")
rd_to_qmd(file.path(example_pkg, "man", "rd_to_qmd.Rd"), pkg = example_pkg)
```

## See Also
Other Conversion functions: `index_to_qmd()`, `rd_to_list()`


