---
title: "Writes the index of the reference pages into a Quarto file"
execute:
  eval: true
  freeze: true
---

## write_reference_index

## Description
Writes the index of the reference pages into a Quarto file


## Usage
```r
write_reference_index(
  pkg = ".",
  folder = NULL,
  index_file = "index.qmd",
  index_template = NULL,
  quarto_file_path = NULL
)
```

## Arguments
|Arguments|Description|
|---|---|
| pkg | Path to the root of the R package. Defaults to `"."`. |
| folder | The target folder to save the new Quarto files to |
| index_file | The name assigned to the resulting index Quarto file |
| index_template | The path to a Quarto file that can be used as the template for the index Quarto file |
| quarto_file_path | Path to the folder containing _quarto.yml. Use when the Quarto project root differs from the package root (e.g. the package lives in a sub-folder of a larger Quarto project). Must be a directory path. Defaults to `NULL`, in which case `pkg` is used. |


## Value
A Quarto file that links to the individual Quarto documentation files





## See Also
Other Quarto file creation: `write_reference()`, `write_reference_pages()`

## Examples
```{r}
library(pkgsite)
example_pkg <- system.file("example", package = "pkgsite")
write_reference_index(pkg = example_pkg, folder = tempdir())
```
