---
title: "Converts the 'Rd' file into Quarto, and writes the file to a specified folder"
execute:
  eval: true
  freeze: true
---

## write_reference_pages

## Description
Converts the 'Rd' file into Quarto, and writes the file to a specified folder


## Usage
```r
write_reference_pages(
  project = ".",
  pkg = NULL,
  folder = "reference",
  examples = TRUE,
  not_run_examples = FALSE,
  template = NULL
)
```

## Arguments
|Arguments|Description|
|---|---|
| project | The path to the root folder of the project. |
| pkg | The path inside the project folder. Use only if the R package itself is in a sub-folder within the project. |
| folder | The target folder to save the new Quarto files to |
| examples | Flag that sets the examples code chuck to be evaluated when the Quarto document is rendered |
| not_run_examples | Flag that sets the "do not run" examples code chuck to be evaluated when the Quarto document is rendered |
| template | The path to a Quarto file that can be used as the template for all of the resulting reference files. If left NULL, `pkgsite` will use its default template. |








